- menu_name: "Services"

- name: "About Theme"
  url: "https://github.com/Phlow/feeling-responsive/"
  title: "Feeling Responsive"

- name: "Documentation"
  url: "https://phlow.github.io/feeling-responsive/documentation/"
  title: "documentation of this theme"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
